# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  VERSION: '0.0.0-default'
  DO_PUBLISH: false
  OUTPUT_DIR: ./dist/lib

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: debug
        run: |
          echo "ref: ${{ github.ref }}"

####### Setup, restore, test, and pack .NET packages
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      - name: Restore solution dependencies
        run: dotnet restore
      - name: Tests
        run: dotnet test --no-restore --project ./Org.Grush.Lib.RecordCollections.Tests
      - name: AOT Tests
        run: ./Org.Grush.Lib.RecordCollections.AotTests/run-aot-test.sh
      - name: Pack
        run: |
          dotnet pack ./Org.Grush.Lib.RecordCollections            -p:PackageVersion=${{ env.VERSION }} --no-restore --output ${{ env.OUTPUT_DIR }}
          dotnet pack ./Org.Grush.Lib.RecordCollections.Newtonsoft -p:PackageVersion=${{ env.VERSION }} --no-restore --output ${{ env.OUTPUT_DIR }}

####### GitHub and NuGet artifact publishing
      - name: Initialize GitHub Release
        if: ${{ DO_PUBLISH }} # TODO
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: ${{ contains(github.ref, '-rc.') }}

      - name: Upload GitHub Release (lib)
        if: ${{ DO_PUBLISH }} # TODO
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.OUTPUT_DIR }}/Org.Grush.Lib.RecordCollections.${{ github.ref }}.nupkg
          asset_name: Org.Grush.Lib.RecordCollections.${{ github.ref }}.nupkg
          asset_content_type: application/zip

      - name: Upload GitHub Release (Newtonsoft)
        if: ${{ DO_PUBLISH }} # TODO
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.OUTPUT_DIR }}/Org.Grush.Lib.RecordCollections.Newtonsoft.${{ github.ref }}.nupkg
          asset_name: Org.Grush.Lib.RecordCollections.Newtonsoft.${{ github.ref }}.nupkg
          asset_content_type: application/zip

      - name: Publish NuGet
        if: ${{ DO_PUBLISH }} # TODO
        run: |
          dotnet nuget push ./dist/lib/*.nupkg

      - name: Publish GitHub Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}

    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
#  publish:
#    needs: [ create-release ]
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        include:
#          - folder: Org.Grush.NasFileCopy.ServerSide
#            project: Org.Grush.NasFileCopy.ServerSide
#            target: linux-x64
#          - folder: Org.Grush.NasFileCopy.ClientSide/Org.Grush.NasFileCopy.ClientSide.Cli
#            project: Org.Grush.NasFileCopy.ClientSide.Cli
#            target: win-x64
#            exeExt: .exe
#    env:
#      EXE_PATH: ${{ matrix.folder }}/bin/Release/net8.0/${{ matrix.target }}/publish/${{ matrix.project }}${{ matrix.exeExt }}
#      ZIP_PATH: ${{ matrix.folder }}/bin/Release/net8.0/${{ matrix.target }}/publish/${{ matrix.project }}_${{ matrix.target }}.zip
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: 8.0.x
#      - name: Restore dependencies
#        run: dotnet restore
#      - name: Publish ${{ matrix.target }}
#        run: dotnet publish ${{ matrix.folder }}/${{ matrix.project }}.csproj --no-restore -c Release -r ${{ matrix.target }} --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true
#
#      - name: Create Zip File
#        uses: papeloto/action-zip@v1
#        with:
#          files: ${{ env.EXE_PATH }}
#          dest: ${{ env.ZIP_PATH }}
#
#      - name: Push to Release
#        uses: csexton/release-asset-action@v2
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          file: ${{ env.ZIP_PATH }}
#          release-url: ${{ needs.create-release.outputs.release_upload_url }}
